### PR TITLE
Allow for default to be NULL and also allow for comments to be added …

### LINKED ISSUE #5: Timestamp conversion fails on MySQL 5.7
By default, MySQL 5.7's SQL modes include "NO_ZERO_DATE" and "NO_ZERO_IN_DATE".  When these SQL modes are set, `CRM_DoctorWhen_Cleanups_ConvertTimestamp->enqueue()` doesn't specify valid default values when `$this->default` is `null`.

This leads to this error on objects where `$this->default` is `null`:
[ERROR 1067 (42000): Invalid default value for](https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at) 'expired_date'.

### PR DESCRIPTION
**Pull request by seamuslee001**
…to columns

this should resolve #5

### CODE REVIEW

**Comment by seamuslee001** [comment]
I ran the test on a local 47 db 
before the table was 
```
| Table                       | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| civicrm_mailing_event_reply | CREATE TABLE `civicrm_mailing_event_reply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `event_queue_id` int(10) unsigned NOT NULL COMMENT 'FK to EventQueue',
  `time_stamp` datetime NOT NULL COMMENT 'When this reply event occurred.',
  PRIMARY KEY (`id`),
  KEY `FK_civicrm_mailing_event_reply_event_queue_id` (`event_queue_id`),
  CONSTRAINT `FK_civicrm_mailing_event_reply_event_queue_id` FOREIGN KEY (`event_queue_id`) REFERENCES `civicrm_mailing_event_queue` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
+-----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
After
```
mysql> show create table civicrm_mailing_event_reply;
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                       | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| civicrm_mailing_event_reply | CREATE TABLE `civicrm_mailing_event_reply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `event_queue_id` int(10) unsigned NOT NULL COMMENT 'FK to EventQueue',
  `time_stamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When this reply event occurred.',
  PRIMARY KEY (`id`),
  KEY `FK_civicrm_mailing_event_reply_event_queue_id` (`event_queue_id`),
  CONSTRAINT `FK_civicrm_mailing_event_reply_event_queue_id` FOREIGN KEY (`event_queue_id`) REFERENCES `civicrm_mailing_event_queue` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

This was also applying the core patch as well. This was with the following sql modes being used 

```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION```

**Comment by adanielvv** [comment]
Fixes #7.

**Comment by MegaphoneJon** [comment]
I just tested this with Civi 4.7.27 and confirm it fixes #5 as well.

**Comment by totten** [comment]
Thank you @seamuslee001 for fixing!  I'm merging since @DanielvV and @MegaphoneJon both give it 👍.

Wish I'd given this a go a bit sooner -- sounds like another person got bit.

**Pull request merged**
